# Generated by Django 4.0.1 on 2022-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.CharField(max_length=122)),
                ('unblocked', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
    ]
