# Generated by Django 4.0.1 on 2022-09-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_block_delete_fruits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='block',
            new_name='Blocks',
        ),
    ]
