# Generated by Django 4.0.1 on 2022-09-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_block_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='unblocked',
        ),
        migrations.AddField(
            model_name='blocks',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
