# Generated by Django 4.0.1 on 2022-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_unblocks_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
