# Generated by Django 4.0.1 on 2022-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blocks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='unblocks',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
