# Generated by Django 4.0.1 on 2022-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fruit_name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('Fruits_description', models.TextField()),
                ('if_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
